baseURL = 'https://0xph03n1x.github.io/'
languageCode = 'en-us'
title = "0xph03n1x's Blog"
theme = "m10c"

[params]
    author = "0xph03n1x"
    description = "All things tech and security."
    favicon = "/favicon.ico"
    avatar = "/img/skull_cap.png"
    menu_item_separator = " | "
    
    [[params.social]]
        icon = "github"
        name = "Github"
        url = "https://github.com/0xph03n1x"
    [[params.social]]
        icon = "twitter"
        name = "Twitter"
        url = "https://twitter.com/pho3n1x86"
    [[params.social]]
        icon = "mastodon"
        name = "Mastodon"
        url = "https://infosec.exchange/@0xph03n1x"
    [[params.social]]
        icon = "box"
        name = "Hack the Box"
        url = "https://app.hackthebox.com/profile/161190"
    [[params.social]]
        icon = "cloud"
        name = "TryHackMe"
        url = "https://tryhackme.com/p/RemyX"

[menu]
    [[menu.main]]
        identifier = "blog"
        name = "Blog"
        url = "/"
        weight = 1
    [[menu.main]]
        identifier = "malware analysis"
        name = "Malware Analysis"
        url = "/malware_analysis/"
        weight = 2
    [[menu.main]]
        identifier = "security research"
        name = "Security Research"
        url = "/security_research/"
        weight = 3
    [[menu.main]]
        identifier = "About"
        name = "About"
        url = "/about/"
        weight = 4
